# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_people', '0019_auto_20180619_0559'),
        ('aldryn_newsblog', '0017_auto_20180911_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_2', to='aldryn_people.Person', verbose_name='second author'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_3', to='aldryn_people.Person', verbose_name='third author'),
        ),
    ]
