# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 08:28
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0018_auto_20180919_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='related',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_newsblog.Article', verbose_name='specific articles'),
        ),
    ]
