# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 08:00
from __future__ import unicode_literals

import aldryn_newsblog.models
from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_categories', '0004_auto_20150623_0859'),
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_people', '0019_auto_20180619_0559'),
        ('aldryn_newsblog', '0019_auto_20180921_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlogJSRelatedPlugin',
            fields=[
                ('cache_duration', models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.")),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('related_authors', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_people.Person', verbose_name='related authors')),
                ('related_categories', sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_categories.Category', verbose_name='related categories')),
                ('related_types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aldryn_newsblog.NewsBlogConfig', verbose_name='related articles')),
            ],
            options={
                'abstract': False,
            },
            bases=(aldryn_newsblog.models.PluginEditModeMixin, 'cms.cmsplugin', models.Model),
        ),
        migrations.RemoveField(
            model_name='newsblogspecificplugin',
            name='cmsplugin_ptr',
        ),
        migrations.DeleteModel(
            name='NewsBlogSpecificPlugin',
        ),
    ]
