# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 05:36
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_newsblog', '0020_auto_20180927_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_related_articles', slotname='newsblog_related_articles', to='cms.Placeholder'),
        ),
    ]
