# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 07:36
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
from django.apps import apps as django_apps
import django.db.models.deletion


def related_articles_placeholder_gen(apps, schema_editor):
    Article = django_apps.get_model('aldryn_newsblog.Article')
    from cms.models import Placeholder
    placeholder_name = 'related_fields'
    placeholder_id_name = '{0}_id'.format(placeholder_name)

    for article in Article.objects.all():
        placeholder_id = getattr(article, placeholder_id_name, None)
        if placeholder_id is not None:
            continue
        placeholder_new = Placeholder.objects.create(slot=placeholder_name)
        setattr(article, placeholder_id_name, placeholder_new.pk)

        article.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_newsblog', '0021_article_related_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_carousel',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_article_carousel', slotname='newsblog_article_carousel', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_sidebar',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_article_sidebar', slotname='newsblog_article_sidebar', to='cms.Placeholder'),
        ),
        #migrations.RunPython(related_articles_placeholder_gen, backwards)
    ]
