# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 07:36
from __future__ import unicode_literals

from django.db import migrations
from django.apps import apps as django_apps


def related_articles_placeholder_gen(apps, schema_editor):
    Article = django_apps.get_model('aldryn_newsblog.Article')
    from cms.models import Placeholder
    placeholder_name = 'related_fields'
    placeholder_id_name = '{0}_id'.format(placeholder_name)

    for article in Article.objects.all():
        placeholder_id = getattr(article, placeholder_id_name, None)
        if placeholder_id is not None:
            continue
        placeholder_new = Placeholder.objects.create(slot=placeholder_name)
        setattr(article, placeholder_id_name, placeholder_new.pk)

        article.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0021_article_related_articles'),
    ]

    operations = [
        migrations.RunPython(related_articles_placeholder_gen, backwards)
    ]
