# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 09:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0025_newsblogjsrelatedplugin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogjsrelatedplugin',
            name='number_of_articles',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Number of articles'),
            preserve_default=False,
        ),
    ]
