# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-15 06:32
from __future__ import unicode_literals

from django.db import migrations


def related_articles_relations_publisher(apps, schema_editor):
    from cms.models.pagemodel import Page
    pages = Page.objects.all()
    for page in pages:
        if not page.publisher_is_draft:
            continue
        for lang in page.get_languages():
            page.publish(lang)

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0027_newsblogjsrelatedplugin_featured'),
    ]

    operations = [
        migrations.RunPython(related_articles_relations_publisher, backwards)
    ]
