# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0029_newsblogjsrelatedplugin_exclude_current_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Uncheck to remove this section from the related articles listing filters.', verbose_name='Available in related articles listing?'),
        ),
    ]
