# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 03:24
from __future__ import unicode_literals

from django.db import migrations
import djangocms_icon.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0030_newsblogconfig_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogjsrelatedplugin',
            name='icon',
            field=djangocms_icon.fields.Icon(blank=True, default='fa-', max_length=255, verbose_name='Icon'),
        ),
    ]
