# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-31 11:58
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('aldryn_newsblog', '0032_newsblogjsrelatedplugin_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_carousel',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_article_carousel', slotname='newsblog_article_carousel', to='cms.Placeholder'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_sidebar',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_article_sidebar', slotname='newsblog_article_sidebar', to='cms.Placeholder'),
        ),
    ]
