# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0033_auto_20181214_0355'),
        ('aldryn_newsblog', '0033_auto_20181231_1158'),
    ]

    operations = [
    ]
