# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 05:56
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('js_services', '0001_initial'),
        ('aldryn_newsblog', '0035_auto_20190205_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogjsrelatedplugin',
            name='related_services',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_services.Service', verbose_name='related services'),
        ),
        migrations.AlterField(
            model_name='newsblogjsrelatedplugin',
            name='related_types',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_newsblog.NewsBlogConfig', verbose_name='related sections'),
        ),
    ]
