# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('js_locations', '0001_initial'),
        ('aldryn_newsblog', '0038_auto_20190401_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='js_locations.Location', verbose_name='location'),
        ),
    ]
