# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 06:03
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        #('js_companies', '0002_auto_20190417_0522'),
        ('aldryn_newsblog', '0040_article_locations'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='newsblogjsrelatedplugin',
            #name='related_companies',
            #field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='js_companies.Company', verbose_name='related companies'),
        #),
    ]
