# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0042_auto_20190429_1705'),
    ]

    operations = [
        #migrations.RemoveField(
            #model_name='article',
            #name='companies',
        #),
        #migrations.RemoveField(
            #model_name='newsblogjsrelatedplugin',
            #name='related_companies',
        #),
    ]
