# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0043_auto_20190430_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogjsrelatedplugin',
            name='related_mediums',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_newsblog.ArticleMedium', verbose_name='medium'),
        ),
        migrations.AddField(
            model_name='newsblogrelatedplugin',
            name='layout',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='layout'),
        ),
        migrations.AddField(
            model_name='newsblogrelatedplugin',
            name='related_articles',
            field=sortedm2m.fields.SortedManyToManyField(blank=True, help_text=None, to='aldryn_newsblog.Article', verbose_name='related articles'),
        ),
        migrations.AddField(
            model_name='newsblogrelatedplugin',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]
