# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0045_article_show_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='show_authors',
        ),
        migrations.AddField(
            model_name='article',
            name='hide_authors',
            field=models.BooleanField(default=False, verbose_name='Hide Authors'),
        ),
    ]
