# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-04 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_newsblog', '0048_auto_20190704_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='This image will only be shown on social channels. Minimum size: 1200x630px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='social share image'),
        ),
    ]
