# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-28 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0050_auto_20190709_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='allow_post',
            field=models.BooleanField(default=False, verbose_name='Allow POST requests'),
        ),
    ]
