# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-01 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0051_auto_20190828_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='show_in_listing',
            field=models.BooleanField(default=True, help_text='Include articles in listing pages and admin selects?', verbose_name='Include in Listings?'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.Article'),
        ),
        migrations.AlterField(
            model_name='newsblogconfigtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.NewsBlogConfig'),
        ),
    ]
