# Generated by Django 2.2.9 on 2020-01-28 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0052_auto_20191001_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='canonical_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='article',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='layout'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_2', to='aldryn_people.Person', verbose_name='second author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_3', to='aldryn_people.Person', verbose_name='third author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aldryn_newsblog.ArticleMedium', verbose_name='medium'),
        ),
        migrations.AlterField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='newsblogjsrelatedplugin',
            name='exclude_current_article',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='newsblogjsrelatedplugin',
            name='featured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='newsblogjsrelatedplugin',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='title_image', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='newsblogjsrelatedplugin',
            name='more_button_is_shown',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show “See More Button”'),
        ),
        migrations.AlterField(
            model_name='newsblogrelatedplugin',
            name='more_button_is_shown',
            field=models.BooleanField(blank=True, default=False, verbose_name='Show “See More Button”'),
        ),
    ]
