# Generated by Django 2.2.10 on 2020-02-19 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_newsblog', '0053_auto_20200128_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='logo_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='logo image'),
        ),
        migrations.AddField(
            model_name='newsblogconfig',
            name='show_logo',
            field=models.BooleanField(default=False, verbose_name='Show Logo'),
        ),
    ]
