# Generated by Django 2.2.10 on 2020-05-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0055_auto_20200312_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='read_time',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Read time'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='author_2_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_trans_2', to='aldryn_people.Person', verbose_name='second author'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='author_3_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_trans_3', to='aldryn_people.Person', verbose_name='third author'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='author_trans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_trans', to='aldryn_people.Person', verbose_name='author'),
        ),
    ]
