# Generated by Django 2.2.12 on 2020-05-27 09:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0056_auto_20200520_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsblogconfig',
            name='custom_fields_settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
