# Generated by Django 2.2.12 on 2020-07-08 09:25

import app_data.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0057_auto_20200527_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlogFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('number', models.PositiveIntegerField(default=25, verbose_name='Number of articles')),
            ],
            options={
                'verbose_name': 'Feed',
                'verbose_name_plural': 'Feeds',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='article',
            name='feeds',
            field=models.ManyToManyField(blank=True, to='aldryn_newsblog.NewsBlogFeed', verbose_name='feeds'),
        ),
        migrations.CreateModel(
            name='NewsBlogFeedTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('app_title', models.CharField(max_length=234, verbose_name='Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_newsblog.NewsBlogFeed')),
            ],
            options={
                'verbose_name': 'Feed Translation',
                'db_table': 'aldryn_newsblog_newsblogfeed_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
