# Generated by Django 2.2.13 on 2020-08-13 15:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0058_auto_20200708_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='custom_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
