# Generated by Django 2.2.17 on 2021-01-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0061_auto_20201125_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='auto_read_time',
            field=models.BooleanField(default=True, help_text='If set then article read time calculated automatic.', verbose_name='Calculate read time'),
        ),
    ]
