# Generated by Django 2.2.24 on 2021-07-16 07:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0062_newsblogconfig_auto_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='svg_image',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.File', verbose_name='SVG Icon'),
        ),
        migrations.AlterField(
            model_name='newsblogjsrelatedplugin',
            name='number_of_articles',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Number of articles'),
        ),
    ]
