# Generated by Django 2.2.24 on 2021-11-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0064_auto_20210915_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogjsrelatedplugin',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='newsblogrelatedplugin',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
