# Generated by Django 3.2.18 on 2023-04-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0065_auto_20211130_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsblogconfig',
            name='show_landing_page',
            field=models.BooleanField(default=False, verbose_name='Show landing page'),
        ),
    ]
