# Generated by Django 2.2.28 on 2023-04-21 09:43

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('aldryn_newsblog', '0066_newsblogconfig_show_landing_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Related Image'),
        ),
    ]
