# Generated by Django 3.2.23 on 2024-02-21 11:53

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_newsblog', '0067_article_related_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bottom_article_sidebar',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsblog_bottom_article_sidebar', slotname='newsblog_bottom_article_sidebar', to='cms.placeholder'),
        ),
    ]
